#!/bin/bash

# Install mongodb on the raspoberry

cd $HOME

curl -O https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.6.0.tgz
mkdir mongodb
tar -zxvf mongodb-linux-x86_64-3.6.0.tgz
rm mongodb-linux-x86_64-3.6.0.tgz
cp -Rp mongodb-linux-x86_64-3.6.0/bin mongodb
rm -rf mongodb-linux-x86_64-3.6.0

echo '
# MongoDB
export PATH=$PATH:$HOME/mongodb/bin
' >> ~/.profile

source ~/.profile
